// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManagementSystem.Data;

#nullable disable

namespace SchoolManagement.Api.Migrations
{
    [DbContext(typeof(SchoolContext))]
    [Migration("20251216172948_SeedAdmin")]
    partial class SeedAdmin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolManagementSystem.Models.Absence", b =>
                {
                    b.Property<int>("IdAbsence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAbsence"));

                    b.Property<DateTime>("DateAbsence")
                        .HasColumnType("datetime2");

                    b.Property<int>("EtudiantId")
                        .HasColumnType("int");

                    b.Property<bool>("Justifiee")
                        .HasColumnType("bit");

                    b.HasKey("IdAbsence");

                    b.HasIndex("EtudiantId");

                    b.ToTable("Absences");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Account", b =>
                {
                    b.Property<int>("IdAccount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAccount"));

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<int?>("AdministrateurId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EtudiantId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProfesseurId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAccount");

                    b.HasIndex("EtudiantId")
                        .IsUnique()
                        .HasFilter("[EtudiantId] IS NOT NULL");

                    b.HasIndex("ParentId");

                    b.HasIndex("ProfesseurId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            IdAccount = 1,
                            Actif = true,
                            DateCreation = new DateTime(2025, 12, 16, 18, 29, 45, 89, DateTimeKind.Local).AddTicks(7258),
                            PasswordHash = "$2a$11$0BXnUI8P5BTdD23ZWJlDY.Wr9YRh0ZDLKWaqVitTB8oDdmru7ByS2",
                            Role = "Admin",
                            Username = "admin@school.com"
                        });
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Administrateur", b =>
                {
                    b.Property<int>("IdAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAdmin"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAdmin");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("Administrateurs");

                    b.HasData(
                        new
                        {
                            IdAdmin = 1,
                            AccountId = 1,
                            Email = "admin@school.com",
                            Nom = "Super",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Classe", b =>
                {
                    b.Property<int>("IdClasse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClasse"));

                    b.Property<string>("AnneeScolaire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomClasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdClasse");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.EmploiDuTemps", b =>
                {
                    b.Property<int>("IdEmploi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmploi"));

                    b.Property<int>("ClasseId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HeureDebut")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HeureFin")
                        .HasColumnType("time");

                    b.Property<string>("Jour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MatiereId")
                        .HasColumnType("int");

                    b.Property<int>("ProfesseurId")
                        .HasColumnType("int");

                    b.HasKey("IdEmploi");

                    b.HasIndex("ClasseId");

                    b.HasIndex("MatiereId");

                    b.HasIndex("ProfesseurId");

                    b.ToTable("EmploisDuTemps");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Etudiant", b =>
                {
                    b.Property<int>("IdEtudiant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEtudiant"));

                    b.Property<int?>("ClasseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEtudiant");

                    b.HasIndex("ClasseId");

                    b.HasIndex("ParentId");

                    b.ToTable("Etudiants");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Matiere", b =>
                {
                    b.Property<int>("IdMatiere")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMatiere"));

                    b.Property<float>("Coefficient")
                        .HasColumnType("real");

                    b.Property<string>("NomMatiere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfesseurId")
                        .HasColumnType("int");

                    b.HasKey("IdMatiere");

                    b.HasIndex("ProfesseurId");

                    b.ToTable("Matieres");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Notification", b =>
                {
                    b.Property<int>("IdNotification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNotification"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateEnvoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdNotification");

                    b.HasIndex("AccountId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Parent", b =>
                {
                    b.Property<int>("IdParent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdParent"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdParent");

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Professeur", b =>
                {
                    b.Property<int>("IdProf")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProf"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProf");

                    b.ToTable("Professeurs");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Absence", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Etudiant", "Etudiant")
                        .WithMany("Absences")
                        .HasForeignKey("EtudiantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etudiant");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Account", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Etudiant", "Etudiant")
                        .WithOne("Account")
                        .HasForeignKey("SchoolManagementSystem.Models.Account", "EtudiantId");

                    b.HasOne("SchoolManagementSystem.Models.Parent", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.HasOne("SchoolManagementSystem.Models.Professeur", "Professeur")
                        .WithMany("Accounts")
                        .HasForeignKey("ProfesseurId");

                    b.Navigation("Etudiant");

                    b.Navigation("Parent");

                    b.Navigation("Professeur");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Administrateur", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Account", "Account")
                        .WithOne("Administrateur")
                        .HasForeignKey("SchoolManagementSystem.Models.Administrateur", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.EmploiDuTemps", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Classe", "Classe")
                        .WithMany("EmploisDuTemps")
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystem.Models.Matiere", "Matiere")
                        .WithMany()
                        .HasForeignKey("MatiereId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystem.Models.Professeur", "Professeur")
                        .WithMany("EmploisDuTemps")
                        .HasForeignKey("ProfesseurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Classe");

                    b.Navigation("Matiere");

                    b.Navigation("Professeur");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Etudiant", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Classe", "Classe")
                        .WithMany("Etudiants")
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SchoolManagementSystem.Models.Parent", "Parent")
                        .WithMany("Enfants")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Classe");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Matiere", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Professeur", "Professeur")
                        .WithMany("Matieres")
                        .HasForeignKey("ProfesseurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professeur");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Notification", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Account", "Destinataire")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destinataire");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Account", b =>
                {
                    b.Navigation("Administrateur");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Classe", b =>
                {
                    b.Navigation("EmploisDuTemps");

                    b.Navigation("Etudiants");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Etudiant", b =>
                {
                    b.Navigation("Absences");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Parent", b =>
                {
                    b.Navigation("Enfants");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Professeur", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("EmploisDuTemps");

                    b.Navigation("Matieres");
                });
#pragma warning restore 612, 618
        }
    }
}
